#!/bin/bash
# ============================================================
# Script deploy MiniCloud lên cloud (Ubuntu/Debian)
# Chạy trên máy cloud sau khi git clone
#
# Usage:
#   chmod +x deploy-cloud.sh
#   ./deploy-cloud.sh
# ============================================================

set -e  # Dừng nếu có lỗi

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}================================================${NC}"
echo -e "${CYAN}  MiniCloud - Cloud Deployment Script${NC}"
echo -e "${CYAN}================================================${NC}"
echo ""

# ── 1. Lấy IP của server ─────────────────────────────────────
echo -e "${YELLOW}[1/5] Detecting server IP...${NC}"
SERVER_IP=$(curl -s ifconfig.me 2>/dev/null || curl -s icanhazip.com 2>/dev/null || hostname -I | awk '{print $1}')
echo -e "${GREEN}  Server IP: ${SERVER_IP}${NC}"
echo ""

# ── 2. Cài Docker nếu chưa có ────────────────────────────────
echo -e "${YELLOW}[2/5] Checking Docker...${NC}"
if ! command -v docker &> /dev/null; then
    echo "  Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    sudo usermod -aG docker $USER
    echo -e "${GREEN}  Docker installed${NC}"
else
    echo -e "${GREEN}  Docker already installed: $(docker --version)${NC}"
fi

if ! command -v docker compose &> /dev/null; then
    echo "  Installing Docker Compose plugin..."
    sudo apt-get install -y docker-compose-plugin
fi
echo ""

# ── 3. Tạo secrets files ─────────────────────────────────────
echo -e "${YELLOW}[3/5] Creating secrets...${NC}"
mkdir -p secrets

create_secret() {
    local file="secrets/$1"
    local desc="$2"
    local default="$3"

    if [ -f "$file" ]; then
        echo -e "  ${GREEN}[SKIP]${NC} $file already exists"
    else
        if [ -n "$default" ]; then
            echo -n "$default" > "$file"
            echo -e "  ${GREEN}[OK]${NC} $file created (default: $default)"
        else
            echo -e "  ${YELLOW}[INPUT]${NC} Enter $desc:"
            read -s value
            echo -n "$value" > "$file"
            echo -e "  ${GREEN}[OK]${NC} $file created"
        fi
    fi
}

create_secret "db_root_password.txt"  "MariaDB root password"    "RootPass@2024!"
create_secret "db_password.txt"       "MariaDB user password"    "DbPass@2024!"
create_secret "kc_admin_password.txt" "Keycloak admin password"  "KcAdmin@2024!"
create_secret "storage_root_user.txt" "MinIO root username"      "minioadmin"
create_secret "storage_root_pass.txt" "MinIO root password"      "MinioPass@2024!"
echo ""

# ── 4. Tạo .env file ─────────────────────────────────────────
echo -e "${YELLOW}[4/5] Creating .env file...${NC}"
cat > .env << EOF
# Auto-generated by deploy-cloud.sh
SERVER_IP=${SERVER_IP}
DB_NAME=minicloud
DB_USER=admin
REDIS_PASSWORD=redis_secret_123
EOF
echo -e "${GREEN}  .env created with SERVER_IP=${SERVER_IP}${NC}"
echo ""

# ── 5. Pull images và start ───────────────────────────────────
echo -e "${YELLOW}[5/5] Starting services...${NC}"
echo "  Pulling images from DockerHub..."
docker compose -f docker-compose.cloud.yml pull

echo "  Starting all services..."
docker compose -f docker-compose.cloud.yml up -d

echo ""
echo -e "${CYAN}================================================${NC}"
echo -e "${GREEN}  Deployment Complete!${NC}"
echo -e "${CYAN}================================================${NC}"
echo ""
echo -e "${YELLOW}Waiting for services to be healthy (60s)...${NC}"
sleep 60

echo ""
echo -e "${CYAN}=== Service Status ===${NC}"
docker compose -f docker-compose.cloud.yml ps --format "table {{.Name}}\t{{.Status}}"

echo ""
echo -e "${CYAN}=== Access URLs ===${NC}"
echo -e "  Website:    ${GREEN}http://${SERVER_IP}/${NC}"
echo -e "  Keycloak:   ${GREEN}http://${SERVER_IP}/auth/${NC}"
echo -e "  Grafana:    ${GREEN}http://${SERVER_IP}/grafana/${NC}"
echo -e "  Prometheus: ${GREEN}http://${SERVER_IP}/prometheus/${NC}"
echo -e "  MinIO:      ${GREEN}http://${SERVER_IP}/minio/${NC}"
echo ""
echo -e "${YELLOW}Note: Keycloak may take 2-3 minutes to fully start${NC}"
echo ""
