global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus tự scrape chính nó
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter — CPU, RAM, Disk, Network của host
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['minicloud-node-exporter:9100']
        labels:
          instance: 'monitoring-node-exporter-server'

  # Flask App — Prometheus metrics từ Flask app (prometheus_flask_exporter)
  - job_name: 'app'
    static_configs:
      - targets: ['10.10.1.12:8081']
    metrics_path: /metrics

  # mysqld-exporter — MariaDB metrics
  - job_name: 'db'
    static_configs:
      - targets: ['minicloud-mysqld-exporter:9104']

  # nginx-prometheus-exporter — nginx connection metrics
  - job_name: 'web'
    static_configs:
      - targets: ['minicloud-nginx-exporter:9113']
