global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus tự scrape chính nó
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.10.3.16:9090']
    metrics_path: /prometheus/metrics

  # Node Exporter — CPU, RAM, Disk, Network của host
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.10.3.19:9100']
        labels:
          instance: 'monitoring-node-exporter-server'

  # Flask App — Prometheus metrics từ Flask app (prometheus_flask_exporter)
  - job_name: 'app'
    static_configs:
      - targets: ['10.10.1.12:8081']
        labels:
          instance: 'app1'
      - targets: ['10.10.1.22:8081']
        labels:
          instance: 'app2'
    metrics_path: /metrics

  # mysqld-exporter — MariaDB metrics
  - job_name: 'db'
    static_configs:
      - targets: ['10.10.2.20:9104']

  # nginx-prometheus-exporter — nginx connection metrics
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['10.10.3.21:9113']
